import type { AuditLog } from "@/types/auditLog";
import { AUDIT_ACTION_LABELS } from "@/types/auditLog";

const STORAGE_KEY = "adminAuditLogs";

// Seed Data 

const now = Date.now();
const daysAgo = (n: number) => new Date(now - n * 86400000).toISOString();

// Demo Admin Personas
const ACTOR_SUPER_ADMIN = {
  id: "admin-001",
  name: "Schedula Admin",
  email: "admin123@schedula.com",
  role: "admin" as const,
  adminRole: "super_admin" as const,
};

const ACTOR_OPS_ADMIN = {
  id: "admin-002",
  name: "Ops Admin",
  email: "ops@schedula.com",
  role: "admin" as const,
  adminRole: "admin" as const,
};

const ACTOR_SUPPORT = {
  id: "admin-003",
  name: "Support Staff",
  email: "support@schedula.com",
  role: "admin" as const,
  adminRole: "support" as const,
};

export const seedAuditLogs: AuditLog[] = [
  {
    id: "al-001",
    timestamp: daysAgo(0.1),
    actor: ACTOR_OPS_ADMIN,
    action: "DOCTOR_VERIFIED",
    actionLabel: AUDIT_ACTION_LABELS.DOCTOR_VERIFIED,
    entityType: "doctor",
    entityId: "doc-3",
    entityName: "Dr. Martin Cole",
    details: "Doctor verification approved by Ops Admin. License PSY1003 verified by Medical Council of India.",
    metadata: { previousStatus: "pending", newStatus: "approved", licenseNumber: "PSY1003" },
    ipAddress: "192.168.1.1",
    severity: "info",
  },
  {
    id: "al-002",
    timestamp: daysAgo(0.5),
    actor: ACTOR_SUPPORT,
    action: "REVIEW_HIDDEN",
    actionLabel: AUDIT_ACTION_LABELS.REVIEW_HIDDEN,
    entityType: "review",
    entityId: "rev-009",
    entityName: "Review by Ethan Brooks on Dr. Anika Rao",
    details: "Reported review hidden after Support Staff moderation. Review flagged for inappropriate content.",
    metadata: { reviewRating: 1, reportCount: 3 },
    ipAddress: "192.168.1.1",
    severity: "warning",
  },
  {
    id: "al-003",
    timestamp: daysAgo(1),
    actor: ACTOR_SUPER_ADMIN,
    action: "NOTIFICATION_BROADCAST",
    actionLabel: AUDIT_ACTION_LABELS.NOTIFICATION_BROADCAST,
    entityType: "notification",
    entityId: "notif-seed-001",
    entityName: "Platform Scheduled Maintenance",
    details: "Broadcast notification sent to all patients (120 recipients) regarding scheduled maintenance window on Sunday 28 Sep.",
    metadata: { target: "all_patients", recipientCount: 120, category: "maintenance" },
    ipAddress: "192.168.1.1",
    severity: "info",
  },
  {
    id: "al-004",
    timestamp: daysAgo(1.5),
    actor: ACTOR_OPS_ADMIN,
    action: "DOCTOR_REJECTED",
    actionLabel: AUDIT_ACTION_LABELS.DOCTOR_REJECTED,
    entityType: "doctor",
    entityId: "doc-7",
    entityName: "Dr. Amara Osei",
    details: "Doctor verification rejected by Ops Admin. Submitted license documents could not be validated with the issuing authority.",
    metadata: { previousStatus: "pending", newStatus: "rejected", rejectionReason: "Documents could not be verified with issuing authority" },
    ipAddress: "192.168.1.1",
    severity: "warning",
  },
  {
    id: "al-005",
    timestamp: daysAgo(2),
    actor: ACTOR_OPS_ADMIN,
    action: "PATIENT_STATUS_TOGGLED",
    actionLabel: AUDIT_ACTION_LABELS.PATIENT_STATUS_TOGGLED,
    entityType: "patient",
    entityId: "pat-5",
    entityName: "Noah Williams",
    details: "Patient account deactivated due to multiple policy violations reported by doctors.",
    metadata: { previousStatus: "active", newStatus: "inactive" },
    ipAddress: "192.168.1.1",
    severity: "warning",
  },
  {
    id: "al-006",
    timestamp: daysAgo(2.5),
    actor: ACTOR_SUPPORT,
    action: "APPOINTMENT_CANCELLED",
    actionLabel: AUDIT_ACTION_LABELS.APPOINTMENT_CANCELLED,
    entityType: "appointment",
    entityId: "apt-1045",
    entityName: "Noah Williams with Dr. Anika Rao",
    details: "Appointment cancelled by Support Staff. Reason: Schedule conflict reported by patient.",
    metadata: { appointmentDate: "2026-08-30", previousStatus: "confirmed", cancellationReason: "Schedule conflict" },
    ipAddress: "192.168.1.1",
    severity: "info",
  },
  {
    id: "al-007",
    timestamp: daysAgo(3),
    actor: ACTOR_OPS_ADMIN,
    action: "DOCTOR_STATUS_TOGGLED",
    actionLabel: AUDIT_ACTION_LABELS.DOCTOR_STATUS_TOGGLED,
    entityType: "doctor",
    entityId: "doc-2",
    entityName: "Dr. Sarah Wilson",
    details: "Doctor account temporarily deactivated for profile review and credential re-verification.",
    metadata: { previousStatus: "active", newStatus: "inactive" },
    ipAddress: "192.168.1.1",
    severity: "warning",
  },
  {
    id: "al-008",
    timestamp: daysAgo(4),
    actor: ACTOR_SUPPORT,
    action: "REVIEW_RESTORED",
    actionLabel: AUDIT_ACTION_LABELS.REVIEW_RESTORED,
    entityType: "review",
    entityId: "rev-005",
    entityName: "Review by Maya Patel on Dr. Prakash Das",
    details: "Previously hidden review restored after Support Staff determined content was within platform guidelines.",
    metadata: { reviewRating: 4 },
    ipAddress: "192.168.1.1",
    severity: "info",
  },
  {
    id: "al-009",
    timestamp: daysAgo(5),
    actor: ACTOR_OPS_ADMIN,
    action: "NOTIFICATION_BROADCAST",
    actionLabel: AUDIT_ACTION_LABELS.NOTIFICATION_BROADCAST,
    entityType: "notification",
    entityId: "notif-seed-003",
    entityName: "Profile Verification Reminder",
    details: "Broadcast notification sent to all doctors (18 recipients) reminding them to complete their profile verification.",
    metadata: { target: "all_doctors", recipientCount: 18, category: "reminder" },
    ipAddress: "192.168.1.1",
    severity: "info",
  },
  {
    id: "al-010",
    timestamp: daysAgo(6),
    actor: ACTOR_OPS_ADMIN,
    action: "DOCTOR_VERIFIED",
    actionLabel: AUDIT_ACTION_LABELS.DOCTOR_VERIFIED,
    entityType: "doctor",
    entityId: "doc-1",
    entityName: "Dr. Prakash Das",
    details: "Doctor verification approved after document review. Specialization: Sr. Psychologist.",
    metadata: { previousStatus: "pending", newStatus: "approved", licenseNumber: "PSY1001" },
    ipAddress: "192.168.1.1",
    severity: "info",
  },
  {
    id: "al-011",
    timestamp: daysAgo(7),
    actor: ACTOR_SUPPORT,
    action: "PAYMENT_REFUNDED",
    actionLabel: AUDIT_ACTION_LABELS.PAYMENT_REFUNDED,
    entityType: "payment",
    entityId: "pay-1058",
    entityName: "Payment by Maya Patel (apt-1042)",
    details: "Refund of ₹500 recorded for cancelled appointment. Refund ID: REFUND-58291001.",
    metadata: { refundAmount: 500, refundId: "REFUND-58291001", reason: "Patient requested cancellation before appointment" },
    ipAddress: "192.168.1.1",
    severity: "info",
  },
  {
    id: "al-012",
    timestamp: daysAgo(8),
    actor: ACTOR_OPS_ADMIN,
    action: "PATIENT_STATUS_TOGGLED",
    actionLabel: AUDIT_ACTION_LABELS.PATIENT_STATUS_TOGGLED,
    entityType: "patient",
    entityId: "pat-3",
    entityName: "Maya Patel",
    details: "Patient account reactivated after account review. Access restored.",
    metadata: { previousStatus: "inactive", newStatus: "active" },
    ipAddress: "192.168.1.1",
    severity: "info",
  },
  {
    id: "al-013",
    timestamp: daysAgo(9),
    actor: ACTOR_SUPPORT,
    action: "REVIEW_HIDDEN",
    actionLabel: AUDIT_ACTION_LABELS.REVIEW_HIDDEN,
    entityType: "review",
    entityId: "rev-012",
    entityName: "Review by Lena Moore on Dr. Sarah Wilson",
    details: "Review flagged and hidden by Support Staff. Patient reported the review contained misleading information.",
    metadata: { reviewRating: 2, reportCount: 1 },
    ipAddress: "192.168.1.1",
    severity: "warning",
  },
  {
    id: "al-014",
    timestamp: daysAgo(10),
    actor: ACTOR_OPS_ADMIN,
    action: "DOCTOR_STATUS_TOGGLED",
    actionLabel: AUDIT_ACTION_LABELS.DOCTOR_STATUS_TOGGLED,
    entityType: "doctor",
    entityId: "doc-4",
    entityName: "Dr. Priya Nair",
    details: "Doctor account reactivated after successful re-verification of credentials.",
    metadata: { previousStatus: "inactive", newStatus: "active" },
    ipAddress: "192.168.1.1",
    severity: "info",
  },
  {
    id: "al-015",
    timestamp: daysAgo(12),
    actor: ACTOR_SUPER_ADMIN,
    action: "NOTIFICATION_BROADCAST",
    actionLabel: AUDIT_ACTION_LABELS.NOTIFICATION_BROADCAST,
    entityType: "notification",
    entityId: "notif-seed-002",
    entityName: "New Feature: Online Consultations Now Available",
    details: "Broadcast notification sent to all patients and doctors (138 total recipients) announcing online consultations feature launch.",
    metadata: { target: "all", recipientCount: 138, category: "announcement" },
    ipAddress: "192.168.1.1",
    severity: "info",
  },
  {
    id: "al-016",
    timestamp: daysAgo(14),
    actor: ACTOR_SUPPORT,
    action: "APPOINTMENT_CANCELLED",
    actionLabel: AUDIT_ACTION_LABELS.APPOINTMENT_CANCELLED,
    entityType: "appointment",
    entityId: "apt-1049",
    entityName: "James Turner with Dr. Prakash Das",
    details: "Appointment cancelled by Support Staff at patient's request due to medical emergency on patient side.",
    metadata: { appointmentDate: "2026-08-31", previousStatus: "confirmed", cancellationReason: "Patient medical emergency" },
    ipAddress: "192.168.1.1",
    severity: "info",
  },
  {
    id: "al-017",
    timestamp: daysAgo(15),
    actor: ACTOR_OPS_ADMIN,
    action: "DOCTOR_VERIFIED",
    actionLabel: AUDIT_ACTION_LABELS.DOCTOR_VERIFIED,
    entityType: "doctor",
    entityId: "doc-5",
    entityName: "Dr. Raj Kumar",
    details: "Doctor verification approved by Ops Admin. Orthopedics specialization confirmed. License RJ2001 validated.",
    metadata: { previousStatus: "pending", newStatus: "approved", licenseNumber: "RJ2001" },
    ipAddress: "192.168.1.1",
    severity: "info",
  },
  {
    id: "al-018",
    timestamp: daysAgo(18),
    actor: ACTOR_SUPPORT,
    action: "PAYMENT_REFUNDED",
    actionLabel: AUDIT_ACTION_LABELS.PAYMENT_REFUNDED,
    entityType: "payment",
    entityId: "pay-1059",
    entityName: "Payment by Sofia Chen (apt-1044)",
    details: "Refund of ₹500 recorded by Support Staff. Doctor unavailable — appointment cancelled by clinic.",
    metadata: { refundAmount: 500, refundId: "REFUND-58301002", reason: "Doctor unavailable — appointment cancelled by clinic" },
    ipAddress: "192.168.1.1",
    severity: "info",
  },
  {
    id: "al-019",
    timestamp: daysAgo(20),
    actor: ACTOR_OPS_ADMIN,
    action: "PATIENT_STATUS_TOGGLED",
    actionLabel: AUDIT_ACTION_LABELS.PATIENT_STATUS_TOGGLED,
    entityType: "patient",
    entityId: "pat-8",
    entityName: "Lena Moore",
    details: "Patient account temporarily suspended pending investigation of reported abuse of platform.",
    metadata: { previousStatus: "active", newStatus: "inactive" },
    ipAddress: "192.168.1.1",
    severity: "critical",
  },
  {
    id: "al-020",
    timestamp: daysAgo(22),
    actor: ACTOR_SUPER_ADMIN,
    action: "DOCTOR_REJECTED",
    actionLabel: AUDIT_ACTION_LABELS.DOCTOR_REJECTED,
    entityType: "doctor",
    entityId: "doc-9",
    entityName: "Dr. Felix Wagner",
    details: "Verification rejected by Super Admin. Degree certificate submitted appears tampered. Escalated to compliance.",
    metadata: { previousStatus: "pending", newStatus: "rejected", rejectionReason: "Degree certificate appears tampered — escalated to compliance" },
    ipAddress: "192.168.1.1",
    severity: "critical",
  },
  {
    id: "al-021",
    timestamp: daysAgo(25),
    actor: ACTOR_SUPER_ADMIN,
    action: "ADMIN_LOGIN",
    actionLabel: AUDIT_ACTION_LABELS.ADMIN_LOGIN,
    entityType: "auth",
    entityId: "admin-001",
    entityName: "Schedula Admin",
    details: "Schedula Admin logged into the Schedula Admin Portal successfully.",
    metadata: { userAgent: "Chrome/127" },
    ipAddress: "192.168.1.1",
    severity: "info",
  },
  {
    id: "al-022",
    timestamp: daysAgo(28),
    actor: ACTOR_SUPPORT,
    action: "REVIEW_HIDDEN",
    actionLabel: AUDIT_ACTION_LABELS.REVIEW_HIDDEN,
    entityType: "review",
    entityId: "rev-018",
    entityName: "Review by Priya Sharma on Dr. Martin Cole",
    details: "Review hidden by Support Staff. Content flagged as spam — identical review posted across 4 doctors.",
    metadata: { reviewRating: 1, reportCount: 4, flagReason: "spam" },
    ipAddress: "192.168.1.1",
    severity: "warning",
  },
  {
    id: "al-023",
    timestamp: daysAgo(30),
    actor: ACTOR_OPS_ADMIN,
    action: "DOCTOR_STATUS_TOGGLED",
    actionLabel: AUDIT_ACTION_LABELS.DOCTOR_STATUS_TOGGLED,
    entityType: "doctor",
    entityId: "doc-6",
    entityName: "Dr. Elena Vasquez",
    details: "Doctor account deactivated at doctor's own request due to sabbatical leave.",
    metadata: { previousStatus: "active", newStatus: "inactive", reason: "Doctor requested deactivation (sabbatical)" },
    ipAddress: "192.168.1.1",
    severity: "info",
  },
  {
    id: "al-024",
    timestamp: daysAgo(35),
    actor: ACTOR_SUPPORT,
    action: "APPOINTMENT_RESCHEDULED",
    actionLabel: AUDIT_ACTION_LABELS.APPOINTMENT_RESCHEDULED,
    entityType: "appointment",
    entityId: "apt-1055",
    entityName: "Alex Smith with Dr. Sarah Wilson",
    details: "Appointment rescheduled by Support Staff at patient's request. New date: 2026-09-20.",
    metadata: { originalDate: "2026-09-10", newDate: "2026-09-20", rescheduleReason: "Patient travel conflict" },
    ipAddress: "192.168.1.1",
    severity: "info",
  },
  {
    id: "al-025",
    timestamp: daysAgo(40),
    actor: ACTOR_SUPPORT,
    action: "PAYMENT_REFUNDED",
    actionLabel: AUDIT_ACTION_LABELS.PAYMENT_REFUNDED,
    entityType: "payment",
    entityId: "pay-1060",
    entityName: "Payment by Alex Smith (apt-1050)",
    details: "Refund of ₹500 recorded by Support Staff. Patient rescheduled and duplicate payment was identified.",
    metadata: { refundAmount: 500, refundId: "REFUND-59031003", reason: "Patient rescheduled and duplicate payment identified" },
    ipAddress: "192.168.1.1",
    severity: "info",
  },
  {
    id: "al-026",
    timestamp: daysAgo(45),
    actor: ACTOR_SUPER_ADMIN,
    action: "ADMIN_USER_CREATED",
    actionLabel: AUDIT_ACTION_LABELS.ADMIN_USER_CREATED,
    entityType: "auth",
    entityId: "admin-002",
    entityName: "Ops Admin",
    details: "New admin account 'Ops Admin' created with role 'admin' by Schedula Admin.",
    metadata: { assignedRole: "admin", targetEmail: "ops@schedula.com" },
    ipAddress: "192.168.1.1",
    severity: "info",
  },
  {
    id: "al-027",
    timestamp: daysAgo(50),
    actor: ACTOR_SUPER_ADMIN,
    action: "PLATFORM_SETTINGS_UPDATED",
    actionLabel: AUDIT_ACTION_LABELS.PLATFORM_SETTINGS_UPDATED,
    entityType: "system",
    entityId: "platform-settings",
    entityName: "Platform Settings",
    details: "Platform configuration updated by Schedula Admin (platform name, commission rate, and maintenance mode settings).",
    metadata: { updatedBy: "Schedula Admin", adminRole: "super_admin" },
    ipAddress: "192.168.1.1",
    severity: "warning",
  },
];

// Storage Helpers
export function loadAuditLogs(): AuditLog[] {
  if (typeof window === "undefined") return seedAuditLogs;
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) {
      let parsed: AuditLog[] = JSON.parse(raw);
      if (parsed.length > 0) {
        // Migrate existing logs that might still lack adminRole or have old placeholder names
        let changed = false;
        parsed = parsed.map((log) => {
          if (log.actor.role === "admin" && (!log.actor.adminRole || log.actor.name === "Admin" || log.actor.name === "Super Admin")) {
            changed = true;
            const adminRole = log.actor.id === "admin-002" ? "admin" : log.actor.id === "admin-003" ? "support" : "super_admin";
            const name = log.actor.id === "admin-002" ? "Ops Admin" : log.actor.id === "admin-003" ? "Support Staff" : "Schedula Admin";
            const email = log.actor.id === "admin-002" ? "ops@schedula.com" : log.actor.id === "admin-003" ? "support@schedula.com" : "admin123@schedula.com";
            return {
              ...log,
              actor: {
                ...log.actor,
                name: log.actor.name === "Admin" || log.actor.name === "Super Admin" ? name : log.actor.name,
                email: log.actor.email === "admin@schedula.com" ? email : log.actor.email,
                adminRole,
              },
            };
          }
          return log;
        });
        if (changed) persistAuditLogs(parsed);
        return parsed;
      }
    }
  } catch { /* ignore */ }
  // First load: persist seed data
  persistAuditLogs(seedAuditLogs);
  return seedAuditLogs;
}

export function persistAuditLogs(logs: AuditLog[]): void {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(logs));
  } catch { /* ignore */ }
}
