import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import type { Payment } from "@/types/payment";
import { getAllPayments, persistPayments } from "@/lib/mock-data/payments";

export interface PaymentsState {
  payments: Payment[];
}

function getInitialPayments(): Payment[] {
  if (typeof window === "undefined") return [];
  try {
    return getAllPayments();
  } catch {
    return [];
  }
}

const initialState: PaymentsState = {
  payments: getInitialPayments(),
};

export const paymentsSlice = createSlice({
  name: "payments",
  initialState,
  reducers: {
    /** Loads payments from localStorage (or seed data fallback). */
    hydratePayments: (state) => {
      state.payments = getAllPayments();
    },

    /**
     * Creates a pending payment for an appointment.
     * If a payment already exists for the appointmentId it is updated in-place
     * to prevent duplicates (e.g. patient opens "Pay Now" more than once).
     */
    createPayment: (state, action: PayloadAction<Payment>) => {
      const existingIndex = state.payments.findIndex(
        (p) => p.appointmentId === action.payload.appointmentId
      );
      if (existingIndex >= 0) {
        state.payments[existingIndex] = {
          ...state.payments[existingIndex],
          ...action.payload,
          updatedAt: new Date().toISOString(),
        };
      } else {
        state.payments.push(action.payload);
      }
      persistPayments(state.payments);
    },

    /**
     * Marks a payment as paid.
     * The transactionId is generated by the caller and included in the payload
     * so appointmentsSlice can mirror it without re-generating.
     *
     * Core rule: Payment Success → Appointment Confirmed
     */
    markPaymentSuccess: (
      state,
      action: PayloadAction<{
        appointmentId: string;
        method: Payment["method"];
        transactionId: string;
      }>
    ) => {
      const payment = state.payments.find(
        (p) => p.appointmentId === action.payload.appointmentId
      );
      if (payment) {
        payment.status = "paid";
        payment.method = action.payload.method;
        payment.transactionId = action.payload.transactionId;
        payment.updatedAt = new Date().toISOString();
      }
      persistPayments(state.payments);
    },

    /**
     * Marks a payment as failed.
     * Core rule: Payment Failed → Appointment remains Pending
     */
    markPaymentFailed: (
      state,
      action: PayloadAction<{
        appointmentId: string;
        method: Payment["method"];
      }>
    ) => {
      const payment = state.payments.find(
        (p) => p.appointmentId === action.payload.appointmentId
      );
      if (payment) {
        payment.status = "failed";
        payment.method = action.payload.method;
        payment.updatedAt = new Date().toISOString();
      }
      persistPayments(state.payments);
    },
  },
});

export const {
  hydratePayments,
  createPayment,
  markPaymentSuccess,
  markPaymentFailed,
} = paymentsSlice.actions;

export default paymentsSlice.reducer;
